using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class rain : MonoBehaviour
{
    int type;
    float size;
    int score;

    // Start is called before the first frame update
    void Start()
    {
        //빗물 위치 랜덤지정
        float x = Random.Range(-2.7f, 2.7f);
        float y = Random.Range(3.0f, 5.0f);
        transform.position = new Vector3(x, y, 0);

        //빗물 종류 설정하기
        type = Random.Range(1, 4);
        {
            if(type == 1)
            {
                size = 1.2f;
                score = 3;
                GetComponent<SpriteRenderer>().color = new Color(100 / 255f, 100 / 255f, 255 / 255f, 255 / 255f);
            }

            else if(type == 2)
            {
                size = 1.0f;
                score = 2;
                GetComponent<SpriteRenderer>().color = new Color(130 / 255f, 130 / 255f, 255 / 255f, 255 / 255f);
            }

            else if(type == 3 )
            {
                size = 0.8f;
                score = -5;
                GetComponent<SpriteRenderer>().color = new Color(255 / 255f, 100 / 255f, 100 / 255f, 255 / 255f);
            }

            else
            {
                size = 0.8f;
                score = 1;
                GetComponent<SpriteRenderer>().color = new Color(150 / 255f, 150 / 255f, 255 / 255f, 255 / 255f);
            }

            transform.localScale = new Vector3(size, size, 0);

        }
    }

    // Update is called once per frame
    void Update()
    {
        
    }

    void OnCollisionEnter2D(Collision2D coll)
    {
        //빗물이 땅바닥이나 르탄을 만나면 사라지도록 하며 점수계산
        if (coll.gameObject.tag == "ground")
        {
            Destroy(gameObject);
        }

        if (coll.gameObject.tag == "Rtan")
        {
            Destroy(gameObject);
            GameManager.I.AddScore(score);
        }
    }
}
